from pathlib import Path
from zipfile import ZipFile
from html import escape as H
import json,base64,csv
OUT=Path(__file__).resolve().parent;ROOT=OUT.parent;DELOITTE=OUT.parents[3]
B=DELOITTE/'outputs'/'productivity10x_correction_20260913';DATA=json.loads((B/'chart_data.json').read_text())
for k in ['gdp','gdp_updated','traffic','traffic_names']:DATA.pop(k)
DATA.pop('eci',None)
DATA['mensa']=json.loads((OUT/'datos'/'mensa_2026-09-15.json').read_text())
DATA['gpqa']['human_expert']=69.7
PREV=B.parent/'copilot_aacc_20260912'
V6=DELOITTE/'2. Managers y Directores'/'01_Sesión Presencial General'/'01_Estrategia_IA'/'02_HTML'/'assets'/'v6'
def img(name):
    f=B/'source_media'/name
    return 'data:image/'+('jpeg' if f.suffix=='.jpg' else 'png')+';base64,'+base64.b64encode(f.read_bytes()).decode()
VIDEO='data:video/mp4;base64,'+base64.b64encode((V6/'cover-traffic-light.mp4').read_bytes()).decode()
POSTER='data:image/jpeg;base64,'+base64.b64encode((V6/'cover-traffic-light-poster.jpg').read_bytes()).decode()
COVER_VIDEO='data:video/mp4;base64,'+base64.b64encode((OUT/'media'/'portada-lineas-verdes.mp4').read_bytes()).decode()
COVER_POSTER='data:image/jpeg;base64,'+base64.b64encode((OUT/'media'/'portada-lineas-verdes-poster.jpg').read_bytes()).decode()
with ZipFile(PREV/'referencia_canonica.docx') as z:LOGO='data:image/png;base64,'+base64.b64encode(z.read('word/media/image1.png')).decode()
fonts=''
for weight,name in [(400,'Regular'),(700,'Bold')]:
    f=Path.home()/'Library'/'Fonts'/f'OpenSans-{name}.ttf'
    fonts+=f"@font-face{{font-family:Open;src:url(data:font/ttf;base64,{base64.b64encode(f.read_bytes()).decode()}) format('truetype');font-weight:{weight};font-display:swap}}"
old_sources=json.loads((PREV/'content.json').read_text())['sources']
SOURCES=[r for r in old_sources if r[0] in ['MS01','MS04','MS11','MS14','AI01','AI02','AI03','AI04']]
for r in SOURCES:
    if r[0]=='AI01':r[4]='CSV descargados el 13/09/2026. Se conserva el dato original y se aplica un corte por fecha de lanzamiento. CC BY.'
SOURCES += [
 ['AI05','Test Mensa Norway · puntuaciones de modelos','TrackingAI · Maxim Lott','https://www.trackingai.org/home','Consulta 15/09/2026. Gráfica de 7 configuraciones verbales con observaciones en septiembre. Media de hasta 7 ejecuciones por configuración; Fable y Astra tienen 1 observación en la media. Se reproduce la conversión y el redondeo del código de TrackingAI. El test público puede estar presente en los datos de entrenamiento. No equivale a un CI humano validado.'],
 ['AI06','Referencia humana en GPQA Diamond','Epoch AI','https://epoch.ai/benchmarks/gpqa-diamond','Expertos con nivel de doctorado: 69,7% en la evaluación humana de GPQA Diamond citada por Epoch AI. Es una referencia de ese protocolo, no de cualquier persona con doctorado.'],
 ['AI07','Mensa IQ Challenge','Mensa International','https://www.mensa.org/mensa-iq-challenge/','Test de práctica orientativo; no permite certificar el CI ni acceder a Mensa. La referencia del percentil 98 se representa aproximadamente como 131 en una distribución con media 100 y desviación típica 15.'],
 ['MS17','Memoria de Copilot','Microsoft Support','https://support.microsoft.com/en-US/Microsoft-365-Copilot/personalize-what-microsoft-365-copilot-remembers','Personalización persistente según funciones habilitadas y configuración. No implica retención íntegra de todos los documentos.'],
 ['MS18','Evaluar una respuesta de Copilot','Microsoft Support','https://support.microsoft.com/en-us/Microsoft-365-Copilot/evaluate-copilot-output-for-clarity-accuracy-tone-and-coverage','Comprobar exactitud, contexto y correspondencia con las fuentes.'],
 ['TO01','Modelos creativos en Firefly','Adobe','https://helpx.adobe.com/ph_en/creative-cloud/apps/generative-ai/non-adobe-models-in-adobe-products.html','Herramientas y modelos para imagen y vídeo. La disponibilidad varía por producto.'],
 ['TO02','Generación de vídeo','Runway','https://help.runwayml.com/hc/en-us/articles/37425232841875-Getting-Started-with-Generative-Video','Ejemplo de herramienta del ecosistema, sin recomendación de contratación.'],
 ['TO03','Síntesis de voz','ElevenLabs','https://elevenlabs.io/docs/overview/capabilities/text-to-speech','Texto a voz. Usar voces y materiales con autorización.'],
 ['TO04','Agentes de programación','GitHub','https://github.com/features/copilot','GitHub Copilot es una herramienta de desarrollo diferente de Microsoft 365 Copilot.'],
 ['TO05','Agentes y automatización','n8n','https://n8n.io/ai-agents/','Ejemplo de flujos que combinan modelos y herramientas.'],
 ['TO06','Agentes de Microsoft 365','Microsoft Adoption','https://adoption.microsoft.com/en-us/ai-agents/agents-in-microsoft-365/','Researcher y Analyst como ejemplos de agentes especializados.']
]
slides=[]
def s(title,body,orig,section,notes='',theme='',sources=None,chart=None):
    slides.append(dict(title=title,body=body,original=orig,section=section,notes=notes,theme=theme,sources=sources or [],chart=chart))
def prompt(t):return '<div class="prompt">'+H(t)+'</div>'
def stat(n,label):return f'<div class="stat"><strong>{n}</strong><span>{label}</span></div>'
s('Productividad 10x','''<img class="cover-poster" src="'''+COVER_POSTER+'''" alt=""><video class="cover-video" muted loop playsinline preload="auto" aria-hidden="true"><source src="'''+COVER_VIDEO+'''" type="video/mp4"></video><div class="cover-shade"></div><div class="cover-title"><p class="overline">Multiplicando tu impacto con IA</p><h1>Productividad</h1><div class="ten">10<span>×</span></div><p class="cover-bottom">Managers y directores<br>Septiembre de 2026</p></div>''',[1],'Productividad','Abre con el título del original. El 10x expresa la ambición del programa; no es una promesa cuantificada de mejora. La pregunta es cómo ampliar el impacto con IA, manteniendo el criterio profesional. El vídeo de fondo es decorativo; si no se reproduce, se ve su imagen fija.','dark cover')
s('Qué vamos a ver hoy','''<div class="agenda-lines"><div class="reveal"><span>01</span><h3>El estado de la IA</h3><p>Capacidades y velocidad</p></div><div class="reveal"><span>02</span><h3>Principios para trabajar con IA</h3><p>Decisiones y conceptos clave</p></div><div class="reveal"><span>03</span><h3>Casos de uso</h3><p>Aplicación práctica con Microsoft 365 Copilot</p></div></div>''',[2],'Productividad','Mantén los tres bloques del original. Esta presentación aporta el marco y las explicaciones. Las prácticas se desarrollan con sus guías y archivos. No es necesario exponer seguidas todas las gráficas para comenzar a practicar.')
s('A qué llamamos productividad','''<div class="question"><span class="smallcaps reveal">Antes de comenzar</span><h2 class="reveal">¿A qué llamamos<br><em>productividad?</em></h2><p class="reveal">Piensa en un día con mucha actividad.<br>¿Qué cambió gracias a tu trabajo?</p></div>''',[4],'Productividad','Deja unos segundos para pensar. Recoge una respuesta sobre cantidad de trabajo y otra sobre resultado. La distinción prepara las dos siguientes diapositivas.','dark question-slide')
s('Hacer más y conseguir más','''<div class="productivity"><div><div class="concept reveal"><span class="smallcaps">Eficiencia</span><h3>Hacer más<br>con menos recursos</h3><p>Reducir el tiempo de preparar un informe.</p></div><div class="concept reveal"><span class="smallcaps green">Eficacia</span><h3>Hacer lo que hay que hacer<br>para llegar al objetivo</h3><p>Preparar el informe que permite decidir.</p></div></div><figure><img src="'''+img('image7.jpg')+'''" alt="Fotografía de una línea de producción incluida en la referencia"><figcaption>La actividad tiene valor cuando sirve a un objetivo.</figcaption></figure></div>''',[5],'Productividad','Conserva la distinción del original entre hacer más rápido y hacer lo necesario para llegar al objetivo. Evita atribuir la frase sobre correr sin avanzar: la referencia no aporta una fuente verificable para esa cita. Ejemplo: un informe más rápido puede seguir siendo innecesario.')
s('La IA es un multiplicador','''<div class="multiplier"><div class="equation" role="img" aria-label="Cero por diez mil es igual a cero"><div><strong>0</strong><span>Valor de la tarea</span></div><b>×</b><div class="factor"><strong class="multiplier-counter" data-target="10000">10.000</strong><span>Capacidad con IA</span></div><b>=</b><div><strong>0</strong><span>Impacto</span></div></div><p class="multiplier-message reveal">Si una tarea no aporta valor,<br>hacerla <em>10.000 veces más rápido</em><br>nos deja en el mismo sitio.</p><p class="multiplier-close reveal">Primero, elegir qué merece la pena hacer.</p></div>''',[],'Productividad','Deja que el multiplicador crezca desde 1 hasta 10.000, mientras el valor de la tarea y el impacto siguen en cero. La IA amplifica nuestra capacidad; el criterio determina dónde aplicarla. La frase propuesta sobre pasar la vida corriendo sin avanzar no se atribuye ni se reproduce como cita: no se ha verificado su autor. Esta ecuación es una metáfora formativa, no una estimación de productividad.','dark multiplier-slide')
s('Una breve introducción a la IA','''<div class="definition"><p class="reveal">Sistemas que aprenden patrones y los utilizan para <em>generar, clasificar, predecir o actuar.</em></p><div class="definition-foot reveal"><h3>En esta sesión</h3><p>IA generativa: producir y transformar contenido a partir de un encargo y de la información disponible.</p></div></div>''',[7],'Fundamentos','Una definición operativa es suficiente. Los modelos pueden producir texto convincente que contenga errores. Una respuesta útil depende de la tarea, el contexto, las fuentes y la revisión. No presentar al modelo como una persona experta universal.','dark',sources=['MS18'])
s('Qué podemos hacer con IA','''<div class="capabilities">'''+''.join(f'<div class="reveal"><span>{i:02}</span><h3>{a}</h3><p>{b}</p></div>' for i,(a,b) in enumerate([('Transcribir','Conversaciones a texto'),('Redactar','Borradores y síntesis'),('Presentar','Narrativa y diapositivas'),('Hablar','Voz y conversación'),('Pensar','Alternativas e hipótesis'),('Analizar','Datos y explicaciones'),('Crear imágenes','Conceptos y edición'),('Crear vídeos','Secuencias y avatares'),('Crear herramientas','Código y aplicaciones'),('Automatizar','Pasos y seguimiento')],1))+'''</div><p class="takeaway">La posibilidad técnica se convierte en valor cuando resuelve una tarea concreta.</p>''',[8],'Fundamentos','Mantén las diez posibilidades del original. Son capacidades del ecosistema de IA, no una lista de funciones garantizadas en cada cuenta Copilot. Las autorizaciones y la integración con los datos del trabajo determinan qué podemos utilizar.',sources=['TO01','TO02','TO03','TO04','TO05','TO06'])

s('Inteligencia y velocidad','''<div class="two-variables"><div class="reveal"><span>01</span><h2>Inteligencia</h2><p>Qué problemas puede resolver<br>y con qué fiabilidad.</p></div><div class="reveal"><span>02</span><h2>Velocidad</h2><p>A qué ritmo cambian<br>esas capacidades.</p></div></div>''',[11],'Inteligencia y velocidad','Esta es la división central de la PPT. Usamos resultados en evaluaciones para hablar de capacidades y fechas de lanzamiento para hablar del ritmo de cambio. Mantener ambas ideas separadas ayuda a interpretar las gráficas.','dark')
s('Los modelos ante el test de Mensa','''<div class="chart-heading"><p>Mensa Norway · septiembre de 2026<br><span>7 configuraciones verbales con resultados este mes</span></p><div class="headline-stat"><strong>151</strong><span>Claude 5.1 Fable · 1 ejecución</span></div></div><div class="chart mensa-chart" id="mensa-chart"></div><p class="chart-foot">TrackingAI · consulta: 15/09/2026. Media de hasta 7 ejecuciones; Fable y Astra: 1. Referencia humana orientativa: no es una certificación de CI.</p>''',[12],'Inteligencia','La campana muestra una distribución humana teórica con media 100 y desviación típica 15. Los puntos sitúan las puntuaciones que TrackingAI calcula en el test Mensa Norway verbalizado. Se muestran siete configuraciones con mediciones en septiembre, sin mezclar visión y texto. No es un ranking exhaustivo ni una comparación psicométrica validada entre humanos y modelos. El test es público y podría estar en el entrenamiento. Fable y Astra tienen una única observación en la media; los demás usan las últimas ejecuciones disponibles, hasta siete. Datos permite consultar fechas, tamaños de muestra y modalidades de todas las configuraciones con resultados en septiembre.',sources=['AI05','AI07'],chart='mensa')
s('Navier–Stokes','''<div class="navier"><p class="overline green">Navier–Stokes · septiembre de 2026</p><h2>Una prueba matemática<br>a escala de agentes</h2><p class="navier-lead">OpenAI anuncia una resolución de la formulación<br>con fuerza externa y su formalización en Lean.</p><div class="news-stats">'''+stat('88 h','hasta la resolución anunciada')+stat('+17 h','formalización y verificación')+stat('≈10.000','agentes en el grupo que la obtuvo')+'''</div><p class="news-limit">Sistema interno de investigación. El anuncio no describe una conversación ordinaria con ChatGPT.</p></div>''',[13],'Inteligencia','El original utilizaba la noticia de las olimpiadas de matemáticas de 2025. Esta actualización recoge el anuncio de OpenAI del 8 de septiembre, revisado el 10. Los tiempos y el número de agentes se atribuyen a ese anuncio. No afirmar concesión de premio ni verificación científica independiente. Distinguir la frontera de investigación de las funciones disponibles en el trabajo.','dark',sources=['AI04'])
s('Preguntas científicas exigentes','''<div class="chart-heading"><p>GPQA Diamond<br><span>Resultados registrados y frontera observada</span></p><div class="headline-stat"><strong>95,8<span>%</span></strong><span>Máxima media registrada</span></div></div><div class="chart" id="gpqa-chart"></div><p class="chart-foot">Línea discontinua: expertos humanos (PhD), 69,7%. Cada punto es una configuración; cambian los modelos y los presupuestos de razonamiento.</p>''',[14],'Inteligencia','La primera gráfica de la diapositiva 14 pasa a tener espacio propio. Se muestran todos los resultados válidos desde 2023 y una línea de máximos sobre mean_score. No utilizar el campo Best score across scorers. Los puntos son observaciones, no una muestra controlada con igual coste.',sources=['AI01','AI06'],chart='gpqa')
s('Cuando un benchmark llega al techo','''<div class="chart-heading"><p>OTIS Mock AIME 2024–2025<br><span>Problemas de matemáticas de competición</span></p><div class="headline-stat"><strong>100<span>%</span></strong><span>En varias configuraciones registradas</span></div></div><div class="chart" id="aime-chart"></div><p class="chart-foot">Una puntuación perfecta en esta batería no significa resolver cualquier problema matemático. La saturación exige evaluaciones más difíciles.</p>''',[14],'Inteligencia','La segunda gráfica del original es Mock AIME, no GPQA ni el examen AIME oficial completo. Se conserva esa identidad. El CSV consultado registra medias de 1,0 en siete configuraciones. Mostrar saturación ayuda a explicar por qué un benchmark pierde capacidad de distinguir modelos.',sources=['AI01'],chart='aime')
s('La autonomía crece en cuestión de meses','''<div class="chart-heading"><p>METR · tareas de software · 50% de éxito<br><span>Duración de la tarea para una persona experta</span></p><div class="headline-stat"><strong>×8,7</strong><span>De 2 h a 17,4 h · abril 2025–abril 2026</span></div></div><div class="chart" id="metr-chart"></div><p class="chart-foot">Escala lineal · estimaciones centrales; intervalos en Datos. Por encima de 16 h, la estimación es poco fiable. Última actualización de METR: 08/05/2026.</p>''',[15],'Inteligencia y velocidad','La curva se dibuja cronológicamente en escala lineal de 0 a 20 horas y muestra el fuerte crecimiento de los modelos de frontera medidos por METR. El horizonte al 50% pasa de 1,996 horas en o3 (16/04/2025) a 17,413 horas en Claude Mythos Preview early (07/04/2026): 8,7 veces en aproximadamente un año. Más de 16 horas son estimaciones poco fiables con la batería actual; los intervalos completos están en Datos y en cada punto. La duración se mide en tiempo humano experto, no en horas de ejecución autónoma del agente. La línea conecta observaciones, no es un ajuste ni una predicción. No se extrapola hasta septiembre.',sources=['AI03'],chart='metr')
s('104 modelos durante 2026','''<div class="launch-head"><strong class="counter" data-target="104">104</strong><p>grupos de modelos del registro de Epoch AI<br>con primera publicación en 2026</p></div><div class="chart launch-chart" id="launch-chart"></div><p class="chart-foot">Una entrada por model_group. 316 filas de variantes agrupadas. Corte: 13/09/2026; septiembre parcial. Es un registro, no un censo mundial.</p>''',[11],'Velocidad','Ampliación solicitada para el bloque de velocidad. Agrupar primero todo el catálogo por model_group y tomar su primera fecha, después filtrar 2026. El resultado sigue siendo 104 al consultar el 13 de septiembre. La última fecha de lanzamiento observada es el 3 de septiembre. El inventario completo está disponible en Datos.',sources=['AI01'],chart='models')
principles=[('Herramientas autorizadas','Utilizar las herramientas y los entornos permitidos para el trabajo.'),('La calidad empieza en la entrada','Aportar datos, contexto y documentos adecuados.'),('Empezar por algo sencillo','Una tarea delimitada permite aprender y comprobar.'),('Revisar los sesgos','Contrastar omisiones, supuestos y trato entre casos.'),('Supervisión humana','Comprobar el resultado antes de utilizarlo en una decisión.'),('Evitar la novedad por sí misma','Elegir la herramienta por la tarea que resuelve.'),('Foco en el resultado','Definir qué debe cambiar y cómo sabremos si funciona.')]
for start,end in [(0,4),(4,7)]:
    body='<div class="principles">'+''.join(f'<div class="reveal"><span>{i+1:02}</span><div><h3>{principles[i][0]}</h3><p>{principles[i][1]}</p></div></div>' for i in range(start,end))+'</div>'
    s('Los siete principios',body,[19],'Principios','Se mantienen los siete principios del original. Se cambia la referencia a ING por la autorización aplicable en Deloitte. Presentarlos como pautas de esta formación, sin atribuir una política corporativa específica que no se ha facilitado.','dark' if start else '',sources=['MS18'])
s('Prompt, tokens y contexto','''<div class="definitions"><div class="reveal"><span>01</span><h3>Prompt</h3><p>El encargo: objetivo, información y condiciones de la respuesta.</p></div><div class="reveal"><span>02</span><h3>Tokens</h3><p>Unidades con las que el modelo procesa el contenido. No equivalen necesariamente a palabras.</p></div><div class="reveal"><span>03</span><h3>Ventana de contexto</h3><p>La información que puede considerar en una interacción. Tiene límites y debe ser relevante.</p></div></div><p class="takeaway">Más contenido no garantiza una mejor respuesta.</p>''',[20],'Conceptos clave','Explicar tokens sin dar una conversión fija de palabras a tokens. El contexto puede incluir instrucciones, conversación y fragmentos de documentos. Evitar afirmar que una ventana amplia garantiza recuperar todos los detalles.',sources=['MS01','MS04'])
s('Memoria y agentes','''<div class="concept-pair"><div class="reveal"><span class="smallcaps green">Memoria</span><h3>Continuidad<br>entre interacciones</h3><p>Preferencias o información guardada según las funciones y controles de la herramienta.</p><p class="muted">No sustituye a seleccionar las fuentes relevantes.</p></div><div class="reveal"><span class="smallcaps green">Agente</span><h3>Un objetivo<br>con instrucciones</h3><p>Combina el modelo con conocimiento o herramientas para resolver una tarea.</p><p class="muted">Su capacidad para actuar depende de sus permisos.</p></div></div>''',[20],'Conceptos clave','Conserva los dos conceptos restantes del original con una explicación útil. Memoria, contexto y documentos de referencia son mecanismos diferentes. Un agente no implica autonomía ilimitada. La configuración y la autorización establecen qué puede hacer.','dark',sources=['MS17','MS14'])
s('Manos a la obra','''<img class="closing-poster" src="'''+POSTER+'''" alt=""><video class="closing-video" muted playsinline preload="auto" aria-hidden="true"><source src="'''+VIDEO+'''" type="video/mp4"></video><div class="closing-shade"></div><div class="closing"><p class="overline reveal">Ahora te toca</p><h2 class="reveal">Manos<br>a la obra<span>.</span></h2><p class="reveal">Del marco a la práctica<br>con Microsoft 365 Copilot.</p></div>''',[25],'Cierre','Cierra la parte expositiva y da paso a la práctica. El semáforo pasa de rojo a verde y se queda en verde: es la señal para empezar a trabajar. Pide que abran la guía del participante y los archivos del caso. Si el vídeo no se reproduce, se muestra su imagen fija en verde.','dark closing-slide')
assert len(slides)==19
source_html=''.join(f'<article id="src-{r[0]}"><h3><a href="{H(r[3])}" target="_blank" rel="noopener">{r[0]} · {H(r[1])} ↗</a></h3><p>{H(r[2])}</p><p>{H(r[4])}</p></article>' for r in SOURCES)
css=fonts+(OUT/'deck.css').read_text();js=(OUT/'deck.js').read_text()
slides_html=''.join(f'<section class="slide {r["theme"]}" id="s{i+1}" aria-label="{i+1}. {H(r["title"])}"><div class="slide-content">'+('' if r["title"] in ["Productividad 10x","A qué llamamos productividad","Inteligencia y velocidad","Navier–Stokes","Manos a la obra"] else f'<h2 class="slide-title">{H(r["title"])}</h2>')+r['body']+f'</div><footer><span>{H(r["section"])}</span><span>{i+1:02d} / {len(slides):02d}</span></footer></section>' for i,r in enumerate(slides))
html=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Deloitte · Productividad 10x</title><meta name="description" content="Productividad 10x. Fundamentos de IA, inteligencia y velocidad, principios y conceptos clave. Contenido actualizado y gráficos animados."><style>{css}</style></head><body><header id="top"><img src="{LOGO}" alt="Deloitte"><span>Productividad 10x</span><div><button id="index-button">Índice</button><button id="notes-button">Notas</button><button id="sources-button">Fuentes</button><button id="data-button">Datos</button><button id="fullscreen-button" aria-label="Pantalla completa">⛶</button></div></header><div id="viewport"><main id="stage">{slides_html}</main></div><nav id="bottom" aria-label="Navegación de la presentación"><div id="progress"></div><div class="nav-left"><button id="prev" aria-label="Anterior">←</button><input id="slide-number" type="number" min="1" max="{len(slides)}" aria-label="Diapositiva"><span>/ {len(slides)}</span><button id="next" aria-label="Siguiente">→</button></div><span id="chapter"></span><div class="nav-right"><button id="replay">Repetir animación</button><span class="date">15.09.2026</span></div></nav><dialog id="panel"><header><h2 id="panel-title"></h2><button id="panel-close" aria-label="Cerrar">×</button></header><div id="panel-body"></div></dialog><template id="source-template">{source_html}</template><div id="tooltip" role="tooltip"></div><script>const SLIDES={json.dumps([{k:v for k,v in r.items() if k!='body'} for r in slides],ensure_ascii=False)}, DATA={json.dumps(DATA,ensure_ascii=False,allow_nan=False)}, SOURCES={json.dumps(SOURCES,ensure_ascii=False)};</script><script>{js}</script></body></html>'''
(ROOT/'01_Deloitte_Productividad_10x.html').write_text(html,encoding='utf-8')
mapping=[]
for orig in range(1,27):
    dest=[str(i+1) for i,r in enumerate(slides) if orig in r['original']]
    action={3:'Omitida: QR de acceso',24:'Omitida: promoción con QR',26:'Omitida: contacto y marca del proveedor'}.get(orig,'Conservada y adaptada al diseño Deloitte')
    if orig==12:action='Actualizada: test Mensa Norway verbalizado, septiembre 2026; referencia humana orientativa'
    if orig in [6,10]:action='Retirada por petición del usuario el 15/09/2026'
    if orig==13:action='Actualizada: noticia de Navier–Stokes sustituye olimpiadas de 2025'
    if orig==14:action='Desdoblada: GPQA y Mock AIME, con todos los resultados válidos del CSV'
    if orig in [19,20]:action='Desdoblada para conservar todo el contenido con mayor legibilidad'
    if orig in [9,16,17,18,21,22,23]:action='Retirada en la versión del 14/09/2026'
    if orig==25:action='Cierre sustituido por «Manos a la obra» con vídeo de fondo'
    mapping.append([orig,', '.join(dest) or '—',action])
with (OUT/'Correspondencia_PPT_HTML.csv').open('w',encoding='utf-8-sig',newline='') as f:
    w=csv.writer(f);w.writerow(['Diapositiva original','Diapositivas HTML','Tratamiento']);w.writerows(mapping)
print(f'Generadas {len(slides)} diapositivas y correspondencia de las 26 originales.')
